### ISSUE TITLE
`x` on Chinese character only removes the first byte

### ISSUE THREAD

**Issue by flux77** [kovisoft/paredit#24]
Related to #13.

Example code:

```scheme
;; 華文。
(display "一二三。")
```

In normal mode, positioning the cursor above the `文` character and pressing `x` results in this:

```scheme
;; 華<96><87>。
(display "一二三。")
```

Same thing happens when deleting the full stop or the Chinese characters in the string.

Surprisingly, deleting the Chinese character here works perfectly:

```scheme
(印 "Dire bonjour à la dame.")  ; After pressing `x`: ( "Dire bonjour à la dame.")
```

I asked about this on the vim StackExchange site ([link](https://vi.stackexchange.com/questions/17853/how-to-delete-chinese-characters-in-lisp-code/17857?noredirect=1#comment30691_17857)). One of the comments there says:

> ... Actually using norm! x instead of lines 1123-1130 should fix it.

**Comment by kovisoft** [comment]
Thanks for reporting this bug. I cannot simply use `norm! x` as advised on StackExchange, because I need to 1. dynamically build the line by specially handling matched and unmatched parens, 2. build the final text to be inserted into the yank register. That's the reason behind the current logic. I'll try to reproduce the bug on my system and fix it (unfortunately I don't have Chinese character set installed, so I could not yet reproduce the problem).

Can you please tell me if:
1. What is the unicode length of the given Chinese characters? 3 bytes?
2. Does the problem occur also when you try to delete the very first Chinese character in the line or only when deleting the second, third, etc. character?

Thanks.

**Comment by kovisoft** [comment]
The problem occurred only when the Chinese characters were inside a comment or string. Fixed in commit https://github.com/kovisoft/paredit/commit/f2d4a87324297182ffc2ada002461857cb0cf7af .

**Comment by flux77** [comment]
@kovisoft Thank you for the fix!
