### ISSUE TITLE
Why does PareditInsertClosing return "\<C-Y>"?

### ISSUE THREAD

**Issue by cwfoo** [kovisoft/paredit#39]
Referring to these lines in `PareditInsertClosing`:

https://github.com/kovisoft/paredit/blob/76c1fb8f8dedccefe8df4bffa099af3d19e25a98/plugin/paredit.vim#L935-L937

What is the purpose of these lines?

These lines cause a bug. Steps to reproduce:

1. Open a Common Lisp file (e.g. `myprog.lisp`).
2. Type `(deb`.
3. Omnicomplete: <kbd>Ctrl</kbd><kbd>x</kbd><kbd>Ctrl</kbd><kbd>o</kbd> (observe that the first completion candidate is `debug`). Do not select any completion candidates.
4. Continue typing: `ug)`.

Observation: when the user types the closing parenthesis (e.g. in step 4 above), the closing parenthesis disappears! This is clearly a mistake.

**Comment by kovisoft** [comment]
The purpose of `"\<C-Y>"` is to simulate pressing <kbd>Ctrl</kbd>+<kbd>Y</kbd> within the popup menu (see `:help popupmenu-keys`). This key combination makes the currently selected match in the popup menu accepted and inserted into the current buffer. This code is executed only when a popup menu is displayed.

When I try to reproduce the problem you described, this is what happens:

3. After pressing <kbd>Ctrl</kbd>+<kbd>x</kbd> <kbd>Ctrl</kbd>+<kbd>o</kbd> a popup menu is displayed, the first candidate `debug` is highlighted in the popup menu and `debug` is immediately written into the lisp buffer.
4. Therefore I don't need to continue typing `ug`, moreover if I type it then it will be appeded at `debug` becoming `debugug`. When I press `)` then the code with `"\<C-Y>"` is executed, it selects `debug` and closes the popup menu and moves the cursor past the closing parenthesis.

If you experience something else then this may be caused by some vim option I'm not aware of. What is your vim version? What is your setting for `:set completeopt?` ? For me it is `completeopt=menu,preview`.

**Comment by cwfoo** [comment]
> What is your setting for `:set completeopt?`

It is `completeopt=menu,noselect`. The problem is caused by the `noselect`.

**Comment by cwfoo** [comment]
@kovisoft Will the patch below fix the problem?

```diff
diff --git a/plugin/paredit.vim b/plugin/paredit.vim
index 60c65fe..6251d49 100644
--- a/plugin/paredit.vim
+++ b/plugin/paredit.vim
@@ -932,7 +932,7 @@ endfunction
 " Insert closing type of a paired character, like ) or ].
 function! PareditInsertClosing( open, close )
     let retval = ""
-    if pumvisible()
+    if pumvisible() && &completeopt !~# 'noinsert\|noselect'
         let retval = "\<C-Y>"
     endif
     let save_ve = &ve
```

There may also be other places that need to handle the case of `noinsert` and `noselect`. For example, `PareditEnter`:

https://github.com/kovisoft/paredit/blob/76c1fb8f8dedccefe8df4bffa099af3d19e25a98/plugin/paredit.vim#L1033-L1037

**Comment by kovisoft** [comment]
Thank you for your kind assistance. I found that `longest` also causes problem, so I added these three options as you suggested to the conditions for the <kbd>)</kbd> and <kbd>Enter</kbd> keys while popup menu is displayed. See commit https://github.com/kovisoft/paredit/commit/bbe8d32d7d46f41bd4d207b8b74dfcf0f87d7b2d

**Comment by cwfoo** [comment]
Thank you for maintaining this plugin.
