### ISSUE TITLE
paredit: Custom keybinding for wrap in parens + add space after `(` + insert mode

### ISSUE THREAD

**Issue by MaxGyver83** [kovisoft/paredit#48]
Almost every time I use `paredit_leader` + `W`, I press `a` afterwards, enter a function name plus a space.

This is why it would like to create a keybinding (p.e. `paredit_leader` + `s`) for `paredit_leader` + `W` + `a` + `space` + `left`.

I guess I need something like this but it does not work:

```vim
call RepeatableNNoRemap(g:paredit_leader . 's', ':<C-U>call PareditWrap("(",")")a<space><left>')
```

Can you tell me how to do this correctly?

**Comment by MaxGyver83** [comment]
I found a way, after resolving the function calls of `RepeatableNNoRemap` and `RepeatableMap`:

```vim
execute 'nnoremap <silent> <buffer> ' . g:paredit_leader . 's :<C-U>call PareditWrap("(",")")\|silent! call repeat#set("' . g:paredit_leader . 's")\|:startinsert<CR><right><space><left>'
```

I think this doesn't work using `RepeatableNNoRemap` because `<right><space><left>` must be appended after the `<CR>` (which is appended in `RepeatableMap`).

**Comment by kovisoft** [comment]
I'm afraid currently it's not possible to make such commands repeatable which enter insert mode. That's because of this bug in vim:
https://github.com/vim/vim/issues/3126

The reason is that vim basically "forgets" about previous actions after entering insert mode, and the dot command will repeat only the text entered in insert mode.

This also causes other issues in paredit, e.g. this one:
https://github.com/kovisoft/paredit/issues/25

I suggest that you define the key mapping without the repeat function.

If you really want to have a repeatable mapping, then all I can come up with is that you define two mappings:
One for entering the function name (something like `let g:function_name=input("Enter function name: ")`).
And you define a new function that combines `PareditWrap` with adding the function name and a space, something like:
```
function! PareditWrap2( open, close )
    call PareditWrap( a:open, a:close)
    let line = getline( '.' )
    let pos = col( '.' )
    call setline( line('.'), line[0:pos-1] . g:function_name . " " . line[pos:-1])
    execute "normal! " . len(g:function_name) . "l"
endfunction
```

But then you need to enter insert mode manually. If you add `startinsert` anywhere, then you again lose the repeatability.

**Comment by MaxGyver83** [comment]
Thank you for the clarification and the `PareditWrap2` function!

With my new mapping, `.` repeats the wrapping plus insert mode plus the extra whitespace. Actually, I'm quite happy with this behavior.

I'll have to used it for a while. Then I'll know if I rather want to repeat this command with the same or a different function name.
